g++ .\src\*.cpp `
    -I "include" `
    -L "lib" `
    -llibopencv_core470 `
    -llibopencv_imgcodecs470 `
    -llibopencv_highgui470 `
    -llibopencv_imgproc470 `
    -llibopencv_videoio470 `
    -llibopencv_objdetect470 `
    -llibopencv_ml470 `
    -o .\bin\main.exe