%YAML:1.0
windowSizeX: 128
windowSizeY: 128

blockSizeX: 32
blockSizeY: 32

blockStrideX: 32
blockStrideY: 32

cellSizeX: 16
cellSizeY: 16

nbins: 13
derivAperture: 1
winSigma: -1
L2HysThreshold: 0.2
gammaCorrection: 1
nlevels: 64
signedGradient: 1

sampleRngSeed: 5346654
sampleSplitRatio: 0.7
